SiSiHouse/Models/Entities/Retail.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SiSiHouse.Resources;

namespace SiSiHouse.Models.Entities
{
    public class Retail
    {
        public string RETAIL_CODE { get; set; }

        public long PRODUCT_ID { get; set; }

        public long PRODUCT_DETAIL_ID { get; set; }

        public int COLOR_ID { get; set; }

        public string SIZE { get; set; }

        public int QUANTITY { get; set; }

        public decimal TOTAL_PRICE { get; set; }

        public DateTime? CREATED_DATE { get; set; }

        public long CREATED_USER_ID { get; set; }

        public DateTime? MODIFIED_DATE { get; set; }

        public long MODIFIED_USER_ID { get; set; }

        public string CREATED_USER { get; set; }

        public string MODIFIED_USER { get; set; }
    }
}

SiSiHouse/ViewModels/ManageProduct/SearchProductModel.cs
using SiSiHouse.Models.Conditions;
using SiSiHouse.Models.Entities;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace SiSiHouse.ViewModels.ManageProduct
{
    public class SearchProductModel
    {
        public ProductCondition Condition { get; set; }

        [DisplayName("Thương hiệu")]
        public IList<Brand> BrandSelectList { get; set; }

        [DisplayName("Phân loại")]
        public IList<Category> CategorySelectList { get; set; }

        public string CallBack { get; set; }

        public SearchProductModel()
        {
            Condition = new ProductCondition();
        }
    }
}

SiSiHouse/ViewModels/ManageProduct/UpdateProductModel.cs
using SiSiHouse.Common;
using SiSiHouse.Models.Entities;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace SiSiHouse.ViewModels.ManageProduct
{
    public class UpdateProductModel
    {
        public Product ProductInfo { get; set; }

        [DisplayName("Xóa")]
        public bool DELETE_FLAG
        {
            get { return (ProductInfo.DELETE_FLAG == Constant.DeleteFlag.DELETE); }
            set { ProductInfo.DELETE_FLAG = (value ? Constant.DeleteFlag.DELETE : Constant.DeleteFlag.NON_DELETE); }
        }

        [DisplayName("Thương hiệu")]
        public IList<SelectListItem> BrandSelectList { get; set; }

        [DisplayName("Phân loại")]
        public IList<SelectListItem> CategorySelectList { get; set; }

        [DisplayName("Tiền tệ")]
        public IList<Money> MoneySelectList { get; set; }

        public IList<Color> ColorSelectList { get; set; }

        public IList<Picture> PictureList { get; set; }

        public IList<ProductDetail> ProductDetailList { get; set; }

        public IList<ProductDetail> ProductQuantityList { get; set; }

        public UpdateProductModel()
        {
            ProductInfo = new Product();
            ProductDetailList = new List<ProductDetail>();
            ProductQuantityList = new List<ProductDetail>();
            PictureList = new List<Picture>();
            BrandSelectList = new List<SelectListItem>();
            CategorySelectList = new List<SelectListItem>();
            MoneySelectList = new List<Money>();
            ColorSelectList = new List<Color>();
        }
    }
}

SiSiHouse/ViewModels/ManageProduct/UpdateRetailModel.cs
using SiSiHouse.Common;
using SiSiHouse.Models.Entities;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace SiSiHouse.ViewModels.ManageProduct
{
    public class UpdateRetailModel
    {
        public Product ProductInfo { get; set; }

        public IList<SelectListItem> ColorSelectListByProduct { get; set; }

        public IList<Retail> RetailList { get; set; }

        public UpdateRetailModel()
        {
            ProductInfo = new Product();
            ColorSelectListByProduct = new List<SelectListItem>();
            RetailList = new List<Retail>();
        }
    }
}

SiSiHouse/Controllers/ManageProductController.cs
using SiSiHouse.Common;
using SiSiHouse.Models.Conditions;
using SiSiHouse.Models.Entities;
using SiSiHouse.Resources;
using SiSiHouse.ViewModels;
using SiSiHouse.ViewModels.ManageProduct;
//using SiSiHouse.ViewModels.ManageProduct;
using SiSiHouse.WorkerServices;
using SiSiHouse.WorkerServices.Impl;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Configuration;
using System.IO;

namespace SiSiHouse.Controllers
{
    public class ManageProductController : ControllerBase
    {
        #region Constructor

        private readonly IManageProductService mainService;

        private readonly ICommonService commonService;


        /// <summary>
        /// Default constructor
        /// </summary>
        public ManageProductController()
            : this(new ManageProductService(), new CommonService())
        {
        }

        /// <summary>
        /// Parameterized constructor
        /// </summary>
        /// <param name="service"></param>
        public ManageProductController(IManageProductService service, ICommonService common)
        {
            this.mainService = service;
            this.commonService = common;
        }

        #endregion

        #region Action Result

        public ActionResult Index()
        {
            var model = new SearchProductModel
            {
                BrandSelectList = this.commonService.GetBrandList(),
                CategorySelectList = this.commonService.GetCategoryList()
            };

            return this.View("List", model);
        }

        public ActionResult Update(long id = 0)
        {
            var model = new UpdateProductModel
            {
                BrandSelectList = this.GetBrandSelectList(),
                CategorySelectList = this.GetCategorySelectList(),
                MoneySelectList = this.commonService.GetMoneyList(),
                ColorSelectList = this.commonService.GetColorList(),
            };

            if (id > 0)
            {
                model.PictureList = this.commonService.GetPictureList(id);

                model.ProductInfo = this.mainService.GetProductInfo(id);
                model.ProductDetailList = this.mainService.GetProductDetailList(id);
                model.ProductQuantityList = this.mainService.GetProductQuantityList(id);
            }

            return this.View("Update", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateData(UpdateProductModel model, IEnumerable<HttpPostedFileBase> pictureFiles)
        {
            List<string> newFiles = new List<string>();
            string srcPath = string.Empty;

            try
            {
                if (ModelState.IsValid)
                {
                    var loginUser = GetLoginUser();

                    model.ProductInfo.MODIFIED_DATE = DateTime.Now;
                    model.ProductInfo.MODIFIED_USER_ID = loginUser.USER_ID;

                    srcPath = Server.MapPath(Path.Combine(ConfigurationManager.AppSettings[ConfigurationKeys.SAVE_PICTURE], model.ProductInfo.PRODUCT_ID.ToString()));
                    int index = 0;

                    foreach (var picture in model.PictureList)
                    {
                        if (picture.PICTURE_ID > 0)
                        {
                            index++;
                        } else {
                            break;
                        }
                    }

                    if (pictureFiles != null)
                    {
                        // save file to destination folder
                        foreach (var file in pictureFiles)
                        {
                            if (file != null)
                            {
                                string newFile = UploadFile.SaveFile(file, srcPath);

                                model.PictureList[index].FILE_PATH = newFile;
                                newFiles.Add(newFile);
                            }

                            index++;
                        }
                    }

                    long newProductID = 0;

                    if (this.mainService.UpdateProductInfo(model.ProductInfo, model.ProductQuantityList, model.PictureList, out newProductID))
                    {
                        string desPath = Server.MapPath(Path.Combine(ConfigurationManager.AppSettings[ConfigurationKeys.SAVE_PICTURE], newProductID.ToString()));

                        // case insert new
                        if (model.ProductInfo.PRODUCT_ID == 0)
                        {
                            // move file from temp folder to new project folder
                            UploadFile.CreateFolder(desPath);

                            foreach (var picture in model.PictureList)
                            {
                                if (!string.IsNullOrEmpty(picture.FILE_PATH))
                                {
                                    UploadFile.MoveFile(Path.Combine(srcPath, picture.FILE_PATH), Path.Combine(desPath, picture.FILE_PATH));
                                }
                            }
                        }
                        else // case update
                        {
                            // delete file changed or deleted
                            foreach (var picture in model.PictureList)
                            {
                                if (picture.PICTURE_ID > 0 && (picture.DELETED.HasValue && picture.DELETED.Value))
                                {
                                    UploadFile.DeleteFile(Path.Combine(desPath, picture.FILE_PATH));
                                }
                            }
                        }

                        JsonResult result = Json(
                            new
                            {
                                statusCode = 201,
                                message = string.Format(Resources.Messages.I002)
                            },
                            JsonRequestBehavior.AllowGet);

                        return result;
                    }
                    else
                    {
                        // delete all file uploaded when get error
                        if (newFiles.Count > 0)
                        {
                            foreach (string fileName in newFiles)
                            {
                                UploadFile.DeleteFile(Path.Combine(srcPath, fileName));
                            }
                        }

                        ModelState.AddModelError("", Resources.Messages.E001);
                    }
                }

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                // delete all file uploaded when get error
                if (newFiles.Count > 0)
                {
                    foreach (string fileName in newFiles)
                    {
                        UploadFile.DeleteFile(Path.Combine(srcPath, fileName));
                    }
                }

                logger.Error(Messages.E001, ex);
                ModelState.AddModelError("", Resources.Messages.E001);
                return new EmptyResult();
            }
        }

        public ActionResult Retail(long id = 0)
        {
            if (id > 0)
            {
                var model = new UpdateRetailModel();

                if (id > 0)
                {
                    model.ProductInfo = this.mainService.GetProductInfo(id);
                    model.ProductInfo.PICTURE = Utility.GetPicturePath(id, model.ProductInfo.PICTURE);
                    model.ColorSelectListByProduct = this.GetColorSelectListByProduct(id);
                }

                return this.PartialView("Retail", model);
            }

            return new EmptyResult();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateRetail(UpdateRetailModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var loginUser = GetLoginUser();

                    model.ProductInfo.MODIFIED_DATE = DateTime.Now;
                    model.ProductInfo.MODIFIED_USER_ID = loginUser.USER_ID;

                    if (this.mainService.UpdateRetail(model.ProductInfo, model.RetailList, false, GetLoginUser().USER_ID))
                    {
                        JsonResult result = Json(
                            new
                            {
                                statusCode = 201,
                                message = "Đã tạo hóa đơn bán lẻ thành công."
                            },
                            JsonRequestBehavior.AllowGet);

                        return result;
                    }
                    else
                    {
                        ModelState.AddModelError("", Resources.Messages.E001);
                    }
                }

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                logger.Error(Messages.E001, ex);
                ModelState.AddModelError("", Resources.Messages.E001);
                return new EmptyResult();
            }
        }

        public ActionResult Delete(long id)
        {
            if (Request.IsAjaxRequest())
            {
                try
                {
                    if (this.mainService.DeleteProduct(id, GetLoginUser().USER_ID))
                    {
                        JsonResult result = Json(
                            new
                            {
                                statusCode = 201,
                                message = "Đã xóa sản phẩm thành công."
                            },
                            JsonRequestBehavior.AllowGet);

                        return result;

SiSiHouse/Views/ManageProduct/List.cshtml
@using SiSiHouse.Common
@using SiSiHouse.Resources
@using System.Configuration;
@using System.IO;
@model SiSiHouse.ViewModels.ManageProduct.SearchProductModel


@Styles.Render("~/Content/table")
@Scripts.Render("~/bundles/plugins/datatables/dataTable")
@Styles.Render("~/Content/CustomControllerCss/ManageProduct")

@{
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/ManagementLayout.cshtml";
    var currentUser = HttpContext.Current.Session[Constant.SESSION_LOGIN_USER] as LoginUser;
}

<section class="content-header product-header">
    <h1 id="title">
        @ViewBag.Title
    </h1>
    <div class="search-form">
        <div class="search-condition form-group row">
            <div class="col-lg-3">
                @Html.LabelFor(m => m.Condition.PRODUCT_CODE, new { @class = "" })
                @Html.TextBoxFor(m => m.Condition.PRODUCT_CODE, new { maxlength = 200, @placeholder = "Mã sản phẩm ...", @class = "input-text" })
            </div>
            <div class="col-lg-3">
                @Html.LabelFor(m => m.Condition.PRODUCT_NAME, new { @class = "" })
                @Html.TextBoxFor(m => m.Condition.PRODUCT_NAME, new { maxlength = 200, @placeholder = "Tên sản phẩm ...", @class = "input-text" })
            </div>
            <div class="col-lg-3">
                <label class="lbl-time-range">Ngày cập nhật</label>
                <div class="input-daterange input-group date datepicker-days">
                    @Html.TextBoxFor(m => m.Condition.FROM, "{0:yyyy/MM/dd}", new { @class = "form-control", maxlength = 10 })
                    <span class="input-group-addon">~</span>
                    @Html.TextBoxFor(m => m.Condition.TO, "{0:yyyy/MM/dd}", new { @class = "form-control", maxlength = 10 })
                </div>
            </div>
            <div class="col-lg-3">
                @Html.CheckBoxFor(m => m.Condition.DELETE_FLAG)
                @Html.LabelFor(m => m.Condition.DELETE_FLAG, new { @class = "" })
            </div>
        </div>
        <div class="search-condition row">
            <div class="col-lg-2">
                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" aria-expanded="false">
                    Giới tính <i class="fa fa-caret-down"></i>
                </a>
                <div class="dropdown-menu row">
                    <ul>
                        @for (int i = 0; i < Constant.Sex.Items.Count; i++)
                        {
                            <li>
                                <label class="control-label">
                                    <input alt="@(i)" class="select-sex" type="checkbox">
                                    @Constant.Sex.Items[i]
                                </label>
                            </li>
                        }
                    </ul>
                    <div class="clear-condition">
                        <i class="fa fa-refresh"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" aria-expanded="false">
                    Thương hiệu <i class="fa fa-caret-down"></i>
                </a>
                <div class="dropdown-menu row">
                    <ul>
                        @for (int i = 0; i < Model.BrandSelectList.Count; i++)
                        {
                            <li>
                                <label class="control-label">
                                    @Html.CheckBoxFor(m => m.BrandSelectList[i].CHECK, new { alt = @Model.BrandSelectList[i].BRAND_ID, @class = "select-brand" })
                                    @Model.BrandSelectList[i].BRAND_NAME
                                </label>
                            </li>
                        }
                    </ul>
                    <div class="clear-condition">
                        <i class="fa fa-refresh"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" aria-expanded="false">
                    Phân loại <i class="fa fa-caret-down"></i>
                </a>
                <div class="dropdown-menu row">
                    <ul>
                        @for (int i = 0; i < Model.CategorySelectList.Count; i++)
                        {
                            <li>
                                <label class="control-label">
                                    @Html.CheckBoxFor(m => m.CategorySelectList[i].CHECK, new { alt = @Model.CategorySelectList[i].CATEGORY_ID, @class = "select-category" })
                                    @Model.CategorySelectList[i].CATEGORY_NAME
                                </label>
                            </li>
                        }
                    </ul>
                    <div class="clear-condition">
                        <i class="fa fa-refresh"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" aria-expanded="false">
                    Trạng thái <i class="fa fa-caret-down"></i>
                </a>
                <div class="dropdown-menu row">
                    <ul>
                        @for (int i = 0; i < Constant.Status.Items.Count; i++)
                        {
                            <li>
                                <label class="control-label">
                                    <input alt="@(i)" class="select-status" type="checkbox">
                                    @Constant.Status.Items[i]
                                </label>
                            </li>
                        }
                    </ul>
                    <div class="clear-condition">
                        <i class="fa fa-refresh"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="search-action row">
            <div class="col-lg-6">
                @if (Constant.Role.ADMIN == currentUser.ROLE_ID)
                {
                    <button type="button" id="btnCreate" class="btn dark"><i class="fa fa-plus"></i> Tạo mới </button>
                }
            </div>
            <div class="col-lg-6 right">
                <button type="button" id="btnSearch" class="btn dark"><i class="fa fa-search"></i> Tìm kiếm</button>
                <button type="button" id="btnClear" class=" btn light"><i class="fa fa-refresh"></i> Làm mới</button>
            </div>
        </div>
    </div>
    <div class="show-hide-search">
        <i class="fa fa-chevron-circle-up"></i>
    </div>
</section>

<div class="product-list data-list row">
    <table id="InfoTable" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Link gốc</th>
                <th>Hình ảnh</th>
                <th>Sản phẩm</th>
                <th>Thông tin</th>
                <th>Hàng trong kho</th>
                <th>Trạng thái</th>
                <th>Giá bán</th>
                <th>Thực giá</th>
                <th>Ngày cập nhật</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div class="modal fade" id="retailContent" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog form-action" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Tạo hóa đơn bán lẻ</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn dark btnCreateRetail"><i class="fa fa-save"></i> Tạo</button>
                <button type="button" class="btn light" data-dismiss="modal"><i class="fa fa-reply"></i> Hủy</button>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/ListProduct")

SiSiHouse/Views/ManageProduct/Retail.cshtml
@using SiSiHouse.Common
@model SiSiHouse.ViewModels.ManageProduct.UpdateRetailModel

@using (Html.BeginForm("UpdateRetail", "ManageProduct", FormMethod.Post, new { @class = "form-horizontal retail-regist" }))
{
    <div id="title"></div>
    @Html.ValidationSummary(false)

    <h4>Thông tin sản phẩm</h4>
    <div class="row form-group">
        <div class="col-lg-3 center">
            <img src="@Model.ProductInfo.PICTURE" class="display-picture" />
        </div>
        <div class="col-lg-9">
            <ul>
                <li>
                    <label>Mã sản phẩm: </label>@Model.ProductInfo.PRODUCT_CODE
                </li>
                <li>
                    <label>Tên sản phẩm: </label>@Model.ProductInfo.PRODUCT_NAME
                </li>
                <li>
                    <label>Thương hiệu: </label>@Model.ProductInfo.BRAND_NAME
                </li>
                <li>
                    <label>Loại sản phẩm: </label>@Model.ProductInfo.CATEGORY_NAME
                </li>
                <li>
                    @Html.HiddenFor(m => m.ProductInfo.SALE_PRICE)
                    <label>Nguyên giá: </label>@Model.ProductInfo.SALE_PRICE.Value.ToString("#,##0") VNĐ
                </li>
                @if (Model.ProductInfo.STATUS_ID.Value.ToString() == Constant.Status.SALE_OFF)
                {
                    <li class="error">
                        @Html.HiddenFor(m => m.ProductInfo.SALE_OFF_PRICE)
                        <label>Giá khuyến mãi: </label>@Model.ProductInfo.SALE_OFF_PRICE.Value.ToString("#,##0") VNĐ
                    </li>
                }
            </ul>
        </div>
    </div>
    <hr />

    <h4>Chi tiết hóa đơn <button type="button" class="btn dark btnAddProduct"><i class="fa fa-plus"></i> Thêm</button></h4>
    <div class="row form-group">
        <table id="tbRetail" class="table table-bordered table-hover dataTable no-footer">
            <thead>
                <tr>
                    <th width="18%">Màu</th>
                    <th width="17%">Size</th>
                    <th width="15%">Trong kho</th>
                    <th width="15%">Số lượng bán</th>
                    <th width="30%">Đơn giá</th>
                    <th width="5%"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DropDownList("color", Model.ColorSelectListByProduct, "Chọn", new { @class = "form-control ddlSelectColor" })
                    </td>
                    <td>
                        <select class="form-control ddlSize" id="size" name="size"></select>
                    </td>
                    <td class="center">
                        <label class="quantity-in-stock control-label"></label>
                    </td>
                    <td>
                        <input type="hidden" class="retail-product-detail-id" value="0" />
                        <input type="text" class="retail-quantity numeric form-control" placeholder=" ... " readonly="readonly" />
                    </td>
                    <td class="right">
                        <div class="input-group">
                            <input class="form-control money right total-price" maxlength="9" type="text" placeholder=" ..." readonly="readonly" />
                            <div class="input-group-addon" title="VNĐ">VNĐ</div>
                        </div>
                    </td>
                    <td class="center">
                        <a class="remove-product"><i class="fa fa-remove error control-label"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <hr />
    
    <h4 class="right">Tổng giá trị hóa đơn: <label id="ordersTotalPrice">0</label> VNĐ</h4>

    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ProductInfo.PRODUCT_ID)
    <input name="ProductInfo.PRODUCT_NAME" type="hidden" value="temp">
    <input name="ProductInfo.PRODUCT_CODE" type="hidden" value="temp">
    <input name="ProductInfo.STATUS_ID" type="hidden" value="1">
    <input id="ProductInfo_PRODUCT_ID" name="ProductInfo.MONEY_TYPE_ID" type="hidden" value="2">
}

<script type="text/javascript">
    $(document).ready(function () {
        ResetArrRetail();
    });

    $(".retail-regist").submit(function (e) {
        var formData = new FormData(this);

        $.ajax({
            url: $(this).attr("action"),
            type: 'POST',
            data: formData,
            mimeType: "multipart/form-data",
            contentType: false,
            cache: false,
            processData: false,
            success: function (response) {
                var data = JSON.parse(response);

                if (data.statusCode == 201) { // update success
                    SiSi.utility.showInformationDialog(Constant.DIALOG.SUSSCES, data.message);
                    $('#retailContent').modal('hide');

                    var dataTable = $('#InfoTable').dataTable();
                    dataTable.fnStandingRedraw();
                }

                if (typeof (data.ErrorMessages) !== 'undefined') // invalid data
                    SiSi.utility.showClientError(data.ErrorMessages, '.modal #title');
            },
            error: function (error) {
                if (error.status == 419) //419: Authentication Timeout
                    SiSi.utility.showInformationDialog(Constant.DIALOG.WARNING, Constant.MESSAGE.CONNECT_TIMEOUT, Constant.URL_REDIRECT_TIMEOUT);
            }
        });

        e.preventDefault(); // prevent Default action
    });

</script>