SiSiHouse/Controllers/ManageBillController.cs
using SiSiHouse.Common;
using SiSiHouse.Models.Conditions;
using SiSiHouse.ViewModels;
using SiSiHouse.ViewModels.ManageStatistics;
using SiSiHouse.WorkerServices;
using SiSiHouse.WorkerServices.Impl;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace SiSiHouse.Controllers
{
    public class ManageBillController : ControllerBase
    {
        #region Constructor

        private readonly IManageStatisticsService mainService;

        private readonly ICommonService commonService;


        /// <summary>
        /// Default constructor
        /// </summary>
        public ManageBillController()
            : this(new ManageStatisticsService(), new CommonService())
        {
        }

        /// <summary>
        /// Parameterized constructor
        /// </summary>
        /// <param name="service"></param>
        public ManageBillController(IManageStatisticsService service, ICommonService common)
        {
            this.mainService = service;
            this.commonService = common;
        }

        #endregion

        #region Action Result
        public ActionResult Index()
        {
            var model = new SearchStatisticsModel
            {
                BrandSelectList = this.commonService.GetBrandList(),
                CategorySelectList = this.commonService.GetCategoryList()
            };

            return this.View("List", model);
        }

        #endregion

        #region Ajax Action
        public ActionResult Search(DataTablesModel model, StatisticsCondition condition)
        {
            if (Request.IsAjaxRequest())
            {
                int totalItem = 0;
                var dataList = this.mainService.GetSalesStatisticsDetail(condition, model, out totalItem);
                IList<object> resultList = new List<object>();

                foreach (var data in dataList)
                {
                    resultList.Add(new object[] {
                        data.PRODUCT_ID
                        , Utility.GetPicturePath(data.PRODUCT_ID, data.PICTURE)
                        , data.PRODUCT_CODE
                        , HttpUtility.HtmlEncode(data.PRODUCT_NAME)
                        , HttpUtility.HtmlEncode(data.BRAND_NAME)
                        , HttpUtility.HtmlEncode(data.CATEGORY_NAME)
                        , HttpUtility.HtmlEncode(data.COLOR_NAME)
                        , HttpUtility.HtmlEncode(data.SIZE)
                        , data.QUANTITY
                        , data.SALES.ToString("#,##0")
                        , data.CREATED_DATE.Value.ToString("yyyy/MM/dd HH:mm:ss")
                        , HttpUtility.HtmlEncode(data.CREATED_USER)
                        , data.RETAIL_CODE
                        , data.PRODUCT_DETAIL_ID
                        , data.STATUS_ID
                    });
                }

                var result = Json(
                    new
                    {
                        sEcho = model.sEcho,
                        iTotalRecords = totalItem,
                        iTotalDisplayRecords = totalItem,
                        aaData = resultList
                    },
                    JsonRequestBehavior.AllowGet);

                return result;
            }

            return new EmptyResult();
        }

        public ActionResult DoAction(BillCondition model)
        {
            if (Request.IsAjaxRequest())
            {
                try
                {
                    if (this.mainService.DoAction(model, GetLoginUser().USER_ID))
                    {
                        string messageSuccess = "Đã " + (model.IS_UNDO ? "trả lại" : "xóa") + " hóa đơn \"" + model.RETAIL_CODE + "\" thành công.";
                        JsonResult result = Json(
                            new
                            {
                                statusCode = 201,
                                message = messageSuccess
                            },
                            JsonRequestBehavior.AllowGet);

                        return result;
                    }
                    else
                    {
                        ModelState.AddModelError("", Resources.Messages.E001);
                    }
                }
                catch (Exception ex)
                {
                    logger.Error(ex);
                    ModelState.AddModelError("", Resources.Messages.E001);
                    return new EmptyResult();
                }
            }

            return new EmptyResult();
        }

        #endregion
    }
}

SiSiHouse/Controllers/ShowController.cs
using SiSiHouse.Common;
using SiSiHouse.Models.Conditions;
using SiSiHouse.ViewModels;
using SiSiHouse.WorkerServices;
using SiSiHouse.WorkerServices.Impl;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiSiHouse.Controllers
{
    public class ShowController : Controller
    {
        #region Constructor

        private readonly IManageProductService mainService;

        private readonly ICommonService commonService;

        /// <summary>
        /// Default constructor
        /// </summary>
        public ShowController()
            : this(new ManageProductService(), new CommonService())
        {
        }

        /// <summary>
        /// Parameterized constructor
        /// </summary>
        /// <param name="service"></param>
        public ShowController(IManageProductService service, ICommonService common)
        {
            this.mainService = service;
            this.commonService = common;
        }

        #endregion

        #region Action
        [AllowAnonymous]
        public ActionResult Index()
        {
            return RedirectToAction("", "Home");
        }

        [AllowAnonymous]
        public ActionResult Collection(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("", "Home");
            }

            CollectionCondition condition = this.CreateCondition(id.ToLower());

            ViewBag.TotalProduct = this.mainService.CountProduct(condition);
            ViewBag.Title = id;
            ViewBag.Type = id;
            ViewBag.SearchValue = "";

            var view = View();

            if (Request.Browser.IsMobileDevice)
            {
                view.MasterName = "~/Views/Shared/MobileLayout.cshtml";
            }

            return view;
        }

        [AllowAnonymous]
        public ActionResult Item(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("", "Home");
            }

            long productID = Convert.ToInt64(id);

            CollectionItemModel model = new CollectionItemModel
            {
                ProductInfo = this.mainService.GetCollectionItem(productID),
                PictureList = this.commonService.GetPictureList(productID)
            };

            if (Convert.ToInt16(Constant.Status.SALE_OFF) == model.ProductInfo.STATUS_ID)
            {
                model.ProductInfo.DISPLAY_PRICE = model.ProductInfo.SALE_OFF_PRICE.HasValue ? model.ProductInfo.SALE_OFF_PRICE.Value.ToString("#,##0") + Constant.VND : "";
            }
            else if (model.ProductInfo.SALE_PRICE.HasValue)
            {
                model.ProductInfo.DISPLAY_PRICE = model.ProductInfo.SALE_PRICE.Value.ToString("#,##0") + Constant.VND;
            }

            foreach (var img in model.PictureList)
            {
                img.IMG_SRC = Utility.GetPicturePath(productID, img.FILE_PATH);
            }

            ViewBag.Title = model.ProductInfo.PRODUCT_NAME;

            string layout = Request.Browser.IsMobileDevice ? "ItemOnMobile" : "Item";
            var view = View(layout, model);

            return view;
        }

        [AllowAnonymous]
        public ActionResult Search(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("", "Home");
            }

            CollectionCondition condition = new CollectionCondition
            {
                SEARCH_VALUE = id
            };

            ViewBag.TotalProduct = this.mainService.CountProduct(condition);
            ViewBag.Title = "Search: " + id;
            ViewBag.Type = "";
            ViewBag.SearchValue = id;

            var view = View("Collection");

            if (Request.Browser.IsMobileDevice)
            {
                view.MasterName = "~/Views/Shared/MobileLayout.cshtml";
            }

            return view;
        }

        #endregion

        #region Ajax Action
        [AllowAnonymous]
        public ActionResult List(string type, string searchValue, int countItem = 0)
        {
            if ((string.IsNullOrEmpty(type) && string.IsNullOrEmpty(searchValue)) || !Request.IsAjaxRequest())
            {
                return new EmptyResult();
            }

            DataTablesModel table = new DataTablesModel
            {
                iDisplayStart = countItem,
                iDisplayLength = Convert.ToInt16(ConfigurationManager.AppSettings[ConfigurationKeys.LIST_ITEMS_PER_PAGE]),
                sColumns = "IMPORT_DATE",
                iSortCol_0 = 0,
                sSortDir_0 = "DESC"
            };
            CollectionCondition condition = this.CreateCondition(type.ToLower());
            condition.SEARCH_VALUE = searchValue;

            var productList = this.mainService.GetCollection(condition, table);
            IList<object> dataList = new List<object>();

            foreach (var data in productList)
            {
                dataList.Add(new object[] {
                    data.PRODUCT_ID
                    , data.PRODUCT_NAME
                    , Utility.GetPicturePath(data.PRODUCT_ID, data.PICTURE_1)
                    , Utility.GetPicturePath(data.PRODUCT_ID, data.PICTURE_2)
                });
            }

            var result = Json(
                     new
                     {
                         data = dataList
                     },
                     JsonRequestBehavior.AllowGet);

            return result;
        }
        #endregion

        #region Private Method
        private CollectionCondition CreateCondition(string key)
        {
            CollectionCondition condition = new CollectionCondition();

            switch (key)
            {
                case Constant.CategoryName.CLOTHES:
                    condition.CATEGORY_TYPE = Constant.CategoryType.CLOTHES;
                    break;
                case Constant.CategoryName.FOOTWEARS:
                    condition.CATEGORY_TYPE = Constant.CategoryType.FOOTWEARS;
                    break;
                case Constant.CategoryName.ACCESSORIES:
                    condition.CATEGORY_TYPE = Constant.CategoryType.ACCESSORIES;
                    break;
                default:
                    condition.CATEGORY_NAME = key;
                    break;
            }

            return condition;
        }

        #endregion
    }
}

SiSiHouse/Views/Shared/ManagementHeader.cshtml
@using SiSiHouse.Common;

@{
    var currentUser = HttpContext.Current.Session[Constant.SESSION_LOGIN_USER] as LoginUser;
}

@if (currentUser != null)
{
    <script>
        Constant.CurrentUserRole = '@currentUser.ROLE_ID';
    </script>
}

<nav>
    <div id="logo">
        <a href="/"></a>
    </div>

    @if (currentUser != null)
    {
        <div class="manage-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="@Url.Action("", "ManageProduct")">
                        SẢN PHẨM
                    </a>
                </li>
                <li class="dropdown">
                    <a href="@Url.Action("", "ManageBill")">
                        HÓA ĐƠN
                    </a>
                </li>
                @if (Constant.Role.ADMIN == currentUser.ROLE_ID)
                {
                    <li class="dropdown">
                        <a href="@Url.Action("", "ManageStatistics")">
                            THỐNG KÊ
                        </a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" aria-expanded="false">
                            QUẢN LÝ
                        </a>
                        <ul class="dropdown-menu row">
                            <li>
                                <a href="@Url.Action("", "ManageBrand")">
                                    THƯƠNG HIỆU
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("", "ManageCategory")">
                                    PHÂN LOẠI
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("", "ManageMoney")">
                                    TIỀN TỆ
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("", "ManageColor")">
                                    MÀU SẢN PHẨM
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Family", "SiSi")">
                                    TÀI KHOẢN
                                </a>
                            </li>
                        </ul>
                    </li>
                }
            </ul>
        </div>

        <div class="navbar-custom-menu dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" aria-expanded="false">
                <i class="glyphicon glyphicon-user pull-right mg-right-10"></i>
            </a>
            <ul class="dropdown-menu login-user">
                <li>
                    <a href="@Url.Action("Personal", "SiSi")" class="text-right">
                        @currentUser.FULL_NAME
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("GetOut", "SiSi")" class="text-right">
                        ĐĂNG XUẤT
                    </a>
                </li>
            </ul>
        </div>
    }
</nav>

SiSiHouse/Views/Shared/ManagementLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/Images/sisi_icon.png" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    <script>
        function GetPath(path) {
            var contentPath = '@Url.Content("~/")';
            var fullPath = path.replace(/^~/, '');

            fullPath = fullPath.replace(/^\//, contentPath);

            return fullPath;
        }
    </script>

    @Styles.Render("~/Content/bootstrap/css/bootstrap")
    @Styles.Render("~/Content/adminLTE/altCss")
    @Styles.Render("~/Content/fontawesome/css/icon")
    @Styles.Render("~/Content/common")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/plugins")
    @Scripts.Render("~/bundles/input")
</head>
<body class="management">
    <header id="header" class="main-header">
        @RenderPage("~/Views/Shared/ManagementHeader.cshtml")
    </header>
    <div class="content-wrapper">
        @RenderBody()
    </div>

    <a id="scrollTop" href="javascript:void(0);" title="Back to Top"></a>
</body>
</html>

SiSiHouse/Views/Shared/MobileHeader.cshtml
@using SiSiHouse.Common;

<div class="mobile-header">
    <a id="menu_button">
        <span></span>
    </a>
    <div id="logo_container">
        <a class="logo-header" href="~/"></a>
    </div>
    <div id="header_right">
        <ul>
            <li>
                <a title="Facebook">
                    <i id="showSearchForm" class="fa fa-search"></i>
                </a>
            </li>
            <li class="separator">|</li>
            <li>
                <a href="https://www.facebook.com/sisihouse.myeyes.yourstyle" target="_blank" title="Facebook">
                    <i class="fa fa-facebook-official"></i>
                </a>
            </li>
            <li class="separator">|</li>
            <li>
                <a href="https://www.instagram.com/si.si.house/" target="_blank" title="Instagram">
                    <i class="fa fa-instagram"></i>
                </a>
            </li>
            <li class="separator">|</li>
            <li>
                <a id="contactUs">
                    <i class="fa fa-info-circle"></i>
                </a>
            </li>
        </ul>
    </div>
</div>

<div id="search_form">
    <div class="search-input row">
        <input type="text" id="txtSearchAll" placeholder="Search">
        <button id="searchAll">OK</button>
    </div>
</div>

<div id="menu_header">
    <div id="main-menu">
        <ul>
            <li class="dropdown">
                <a class="has-sub-menu">
                    CLOTHES
                </a>
                <div class="sub-menu-content">
                    <ul class="sub-menu">
                        <li>
                            <a href="@Url.Action("Collection", "Show", new { id = "Clothes" })"><i class="fa fa-angle-right"></i> View All</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Collection", "Show", new { id = "Coats" })"><i class="fa fa-angle-right"></i> Coats</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Collection", "Show", new { id = "Jackets" })"><i class="fa fa-angle-right"></i> Jackets</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Collection", "Show", new { id = "Blazers" })"><i class="fa fa-angle-right"></i> Blazers</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> SweatShirts</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Sweaters</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Shirts</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> T-Shirts</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Polos</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Jeans</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Trousers</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Shorts</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="dropdown">
                <a class="has-sub-menu">
                    FOOTWEARS
                </a>
                <div class="sub-menu-content">
                    <ul class="sub-menu">
                        <li>
                            <a href="@Url.Action("Collection", "Show", new { id = "Footwears" })"><i class="fa fa-angle-right"></i> View All</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Shoes</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Moccasins</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Sneakers</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Boots</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Others</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="dropdown">
                <a class="has-sub-menu">
                    ACCESSORIES
                </a>
                <div class="sub-menu-content">
                    <ul class="sub-menu">
                        <li>
                            <a href="@Url.Action("Collection", "Show", new { id = "Accessories" })"><i class="fa fa-angle-right"></i> View All</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Bags</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Belts</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Glasses</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Hats</a>
                        </li>
                        <li>
                            <a><i class="fa fa-angle-right"></i> Others</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="dropdown">
                <a>
                    LOOKBOOK
                </a>
            </li>
            <li class="dropdown">
                <a href="https://www.facebook.com/sisihouse.myeyes.yourstyle" target="_blank">
                    FACEBOOK
                </a>
            </li>
        </ul>
    </div>
</div>

<div id="menu_layer"></div>

SiSiHouse/Views/Shared/MobileLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/Images/sisi_icon.png" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    <script>
        function GetPath(path) {
            var contentPath = '@Url.Content("~/")';
            var fullPath = path.replace(/^~/, '');

            fullPath = fullPath.replace(/^\//, contentPath);

            return fullPath;
        }
    </script>

    @Styles.Render("~/Content/bootstrap/css/bootstrap")
    @Styles.Render("~/Content/adminLTE/altCss")
    @Styles.Render("~/Content/fontawesome/css/icon")
    @Styles.Render("~/Content/common")
    @Styles.Render("~/Content/Shop")
    @Styles.Render("~/Content/Mobile")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery/plugins")
    @Scripts.Render("~/bundles/input")
    @Scripts.Render("~/bundles/MobileCmEvent")

</head>
<body class="mobile">
    <div class="mobile-content">
        @RenderPage("~/Views/Shared/MobileHeader.cshtml")
        @RenderBody()
    </div>

    <div id="mdContactUs" class="modal fade" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <i id="closeContact" class="fa fa-close"></i>
                    <div class="text-center">
                        <h3>CONTACT</h3>
                    </div>
                    <hr />
                    <div class="text-center">
                        <div>
                            <i class="fa fa-building"></i>
                        </div>
                        <div>0974220985 (Tùng)</div>
                        <div>Nguyễn Khang, Hà Nội</div>
                        <div>Monday to Friday: 16:30 – 20:00</div>
                        <div>Saturday to Sunday: 11:00 – 18:00</div>
                    </div>
                    <br />
                    <div class="text-center">
                        <div>
                            <i class="fa fa-university"></i>
                        </div>
                        <div>Ngân hàng Vietcombank</div>
                        <div>Tên tài khoản: Phạm Sĩ Tùng</div>
                        <div>Số tài khoản: 0301000311770</div>
                        <div>Chi nhánh: VCB Hoàn Kiếm</div>
                    </div>
                    <hr />
                    <div class="text-center">
                        <div>Follow us</div>
                        <div class="follow-us">
                            <a href="https://www.facebook.com/sisihouse.myeyes.yourstyle" target="_blank" title="Facebook">
                                <i class="fa fa-facebook-official"></i>
                            </a>
                            <a href="https://www.instagram.com/si.si.house/" target="_blank" title="Instagram">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

SiSiHouse/Views/Shared/_Footer.cshtml
<footer class="main-footer noselect">
    <div>
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#">
                    Shopping Guide
                </a>
            </li>
            <li class="dropdown">
                <a href="#">
                    Contact Us
                </a>
            </li>
        </ul>
    </div>
    @*<div class="pull-right text-right">
        <ul>
            <li class="dropdown">
                Follow Us 
                <a href="https://www.facebook.com/sisihouse.myeyes.yourstyle" target="_blank" title="Facebook">
                    <i class="fa fa-facebook-official"></i> 
                </a>
                <a href="javascript:void(0);" target="_blank" title="Instagram">
                    <i class="fa fa-instagram"></i>
                </a>
            </li>
        </ul>
    </div>*@
</footer>

SiSiHouse/Views/Shared/_Header.cshtml
@using SiSiHouse.Common;

<div id="header-menu">
    <div id="search">
        <i id="searchAll" class="fa fa-search"></i>
        <input type="text" id="txtSearchAll" placeholder="Search">
    </div>

    <div id="general-menu">
        <ul>
            <li>
                <a href="https://www.facebook.com/sisihouse.myeyes.yourstyle" target="_blank" title="Facebook">
                    <i class="fa fa-facebook-official"></i>
                </a>
            </li>
            <li class="separator">|</li>
            <li>
                <a href="https://www.instagram.com/si.si.house/" target="_blank" title="Instagram">
                    <i class="fa fa-instagram"></i>
                </a>
            </li>
            <li class="separator">|</li>
            <li>
                <a id="contactUs">
                    Contact Us
                </a>
            </li>
        </ul>
    </div>
</div>

<nav>
    <div id="logo">
        <a href="~/" title="SiSi House"></a>
    </div>
    <div id="main-menu">
        <ul>
            <li class="dropdown">
                <a href="@Url.Action("Collection", "Show", new { id = "Clothes" })" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200" aria-expanded="false" data-sub-menu-id="1">
                    CLOTHES
                </a>
            </li>
            <li class="dropdown">
                <a href="@Url.Action("Collection", "Show", new { id = "Footwears" })" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200" aria-expanded="false" data-sub-menu-id="2">
                    FOOTWEARS
                </a>
            </li>
            <li class="dropdown">
                <a href="@Url.Action("Collection", "Show", new { id = "Accessories" })" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200" aria-expanded="false" data-sub-menu-id="3">
                    ACCESSORIES
                </a>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200" aria-expanded="false">
                    LOOKBOOK
                </a>
            </li>
            <li class="dropdown">
                <a href="https://www.facebook.com/sisihouse.myeyes.yourstyle" target="_blank" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200" aria-expanded="false">
                    FACEBOOK
                </a>
            </li>
        </ul>
    </div>
    <div id="sub-menu">
        <div class="sub-menu-content 1">
            <ul class="sub-menu">
                <li>
                    <a href="@Url.Action("Collection", "Show", new { id = "Coats" })">COATS</a>
                </li>
                <li>
                    <a href="@Url.Action("Collection", "Show", new { id = "Jackets" })">JACKETS</a>
                </li>
                <li>
                    <a href="@Url.Action("Collection", "Show", new { id = "Blazers" })">BLAZERS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>SWEATSHIRTS</a>
                </li>
                <li>
                    <a>SWEATERS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>SHIRTS</a>
                </li>
                <li>
                    <a>T-SHIRTS</a>
                </li>
                <li>
                    <a>POLOS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>JEANS</a>
                </li>
                <li>
                    <a>TROUSERS</a>
                </li>
                <li>
                    <a>SHORTS</a>
                </li>
            </ul>
        </div>
        <div class="sub-menu-content 2">
            <ul class="sub-menu">
                <li>
                    <a>SHOES</a>
                </li>
                <li>
                    <a>MOCCASINS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>SNEAKERS</a>
                </li>
                <li>
                    <a>BOOTS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>OTHERS</a>
                </li>
            </ul>
        </div>
        <div class="sub-menu-content 3">
            <ul class="sub-menu">
                <li>
                    <a>BAGS</a>
                </li>
                <li>
                    <a>BELTS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>GLASSES</a>
                </li>
                <li>
                    <a>HATS</a>
                </li>
            </ul>
            <ul class="sub-menu">
                <li>
                    <a>OTHERS</a>
                </li>
            </ul>
        </div>
    </div>
</nav>